package providerroutes

import (
	"encoding/json"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

// Cross-language parity fixture (task P2.10 / test-plan T-10..T-13).
//
// # Why Go exports and TS compares, rather than each side writing expectations
//
// Two hand-written expectation sets are two implementations that can be wrong
// together — P21's lesson, where a fake written to match the provider hid five
// shipped defects behind a green suite. Here the shape of the risk is identical:
// the whole point of this change is "let Go and TS read the same table", and the
// cheapest way to fake that is for both to be written by the same person on the
// same afternoon with the same misunderstanding.
//
// So Go writes the ANSWERS and the TS test only checks agreement. There is
// exactly one place expectations come from.
//
// 🔴 The negative cases carry the weight. `ByProviderProtocol` returning
// ok=false when a pair has several rows and no declared default is a REFUSAL
// the Go side makes on purpose (source comment: "there is no truthful default;
// return ok=false instead of making YAML insertion order observable"). The
// easiest TS bug is `endpoints[0]` — which silently turns YAML row order into a
// routing decision, and would agree with Go on every positive case.

type crossLangAnswers struct {
	// Generated is a note, not data: it exists so a reviewer opening the file
	// knows it is machine-written and how to regenerate it.
	Note string `json:"_note"`

	// ProvidersForProtocol: protocol → providers (yaml order), full table.
	ProvidersForProtocol map[string][]string `json:"providers_for_protocol"`
	// ProtocolsForProvider: provider → protocols (yaml order), full table.
	ProtocolsForProvider map[string][]string `json:"protocols_for_provider"`
	// ByProviderProtocol: the FULL cartesian product, ok=false rows included.
	ByProviderProtocol []crossLangPair `json:"by_provider_protocol"`
	// EffectiveUpstream: every row's base_url+version, keyed host+path_prefix.
	EffectiveUpstream []crossLangUpstream `json:"effective_upstream"`

	// SyntheticDefaults exercises the decision the REAL table cannot.
	//
	// The shipped table satisfies I-5, so every ok=false above comes from a pair
	// that simply does not exist — where "return undefined" is trivially right
	// and a `rows[0]` implementation would agree, because the row set is empty.
	// The case that actually separates a correct implementation from `rows[0]`
	// is "several rows, none flagged default", and the table deliberately
	// contains none. These synthetic row sets supply it.
	SyntheticDefaults []crossLangSynthetic `json:"synthetic_defaults"`
}

// crossLangSynthetic is one hand-built row set plus the answer Go's
// ByProviderProtocol logic gives for it. TS runs pickDefaultEndpoint over the
// same rows and must produce the same verdict.
type crossLangSynthetic struct {
	Name string `json:"name"`
	Why  string `json:"why"`
	Rows []struct {
		URL        string `json:"url"`
		Host       string `json:"host"`
		PathPrefix string `json:"pathPrefix"`
		IsDefault  bool   `json:"isDefault"`
	} `json:"rows"`
	// WantURL is "" when the correct answer is a refusal.
	WantURL string `json:"want_url"`
	WantOK  bool   `json:"want_ok"`
}

type crossLangPair struct {
	Provider string `json:"provider"`
	Protocol string `json:"protocol"`
	OK       bool   `json:"ok"`
	// URL is "" when OK is false. A TS implementation that falls back to the
	// first endpoint produces a non-empty URL here and fails.
	URL string `json:"url"`
}

type crossLangUpstream struct {
	Host       string `json:"host"`
	PathPrefix string `json:"path_prefix"`
	Provider   string `json:"provider"`
	Protocol   string `json:"protocol"`
	URL        string `json:"url"`
}

func buildCrossLangAnswers() crossLangAnswers {
	tbl := Default()

	providers := map[string]bool{}
	protocols := map[string]bool{}
	for _, r := range tbl.All() {
		providers[strings.ToLower(r.Provider)] = true
		protocols[strings.ToLower(r.Protocol)] = true
	}
	sorted := func(m map[string]bool) []string {
		out := make([]string, 0, len(m))
		for k := range m {
			out = append(out, k)
		}
		sort.Strings(out)
		return out
	}
	providerList, protocolList := sorted(providers), sorted(protocols)

	ans := crossLangAnswers{
		Note: "GENERATED by pkg/providerroutes TestExportCrossLangAnswers " +
			"(AIKEY_REGEN_CROSSLANG=1). Go is the single source of these expectations; " +
			"the TS side only checks agreement. Do not hand-edit.",
		ProvidersForProtocol: map[string][]string{},
		ProtocolsForProvider: map[string][]string{},
	}
	for _, p := range protocolList {
		got := tbl.ProvidersForProtocol(p)
		if got == nil {
			got = []string{}
		}
		ans.ProvidersForProtocol[p] = got
	}
	for _, p := range providerList {
		got := tbl.ProtocolsForProvider(p)
		if got == nil {
			got = []string{}
		}
		ans.ProtocolsForProvider[p] = got
	}
	// The FULL cartesian product, not just the pairs that exist. The pairs that
	// do NOT exist are exactly where a "return the first endpoint" bug hides.
	for _, prov := range providerList {
		for _, proto := range protocolList {
			route, ok := tbl.ByProviderProtocol(prov, proto)
			url := ""
			if ok {
				url = EffectiveUpstream(route)
			}
			ans.ByProviderProtocol = append(ans.ByProviderProtocol, crossLangPair{
				Provider: prov, Protocol: proto, OK: ok, URL: url,
			})
		}
	}
	for _, r := range tbl.All() {
		ans.EffectiveUpstream = append(ans.EffectiveUpstream, crossLangUpstream{
			Host: r.Host, PathPrefix: r.PathPrefix, Provider: r.Provider,
			Protocol: r.Protocol, URL: EffectiveUpstream(r),
		})
	}
	ans.SyntheticDefaults = buildSyntheticDefaults()
	return ans
}

// buildSyntheticDefaults runs Go's real ByProviderProtocol over hand-built
// tables covering the branches the shipped YAML does not reach.
func buildSyntheticDefaults() []crossLangSynthetic {
	type scenario struct {
		name, why, yaml string
	}
	scenarios := []scenario{
		{
			name: "two rows, neither flagged default",
			why:  "THE case. A rows[0] implementation returns the first URL here; the correct answer is a refusal, because nothing in the YAML says which endpoint is canonical and row order is not a decision anybody made.",
			yaml: `provider_routes:
  - { host: "a.example.com", path_prefix: "/x", protocol: anthropic, provider: synth, base_url: "https://a.example.com/x", version: "/v1" }
  - { host: "b.example.com", path_prefix: "/x", protocol: anthropic, provider: synth, base_url: "https://b.example.com/x", version: "/v1" }
`,
		},
		{
			name: "two rows, both flagged default",
			why:  "An over-eager edit. Two declared defaults is as ambiguous as none; refuse rather than take the first flagged one.",
			yaml: `provider_routes:
  - { host: "a.example.com", path_prefix: "/x", protocol: anthropic, provider: synth, base_url: "https://a.example.com/x", version: "/v1", default: true }
  - { host: "b.example.com", path_prefix: "/x", protocol: anthropic, provider: synth, base_url: "https://b.example.com/x", version: "/v1", default: true }
`,
		},
		{
			name: "two rows, exactly one flagged default",
			why:  "The normal multi-endpoint shape (minimax, moonshot, together). Must resolve to the flagged row — NOT to the first row, which here is deliberately the un-flagged one.",
			yaml: `provider_routes:
  - { host: "a.example.com", path_prefix: "/x", protocol: anthropic, provider: synth, base_url: "https://a.example.com/x", version: "/v1" }
  - { host: "b.example.com", path_prefix: "/x", protocol: anthropic, provider: synth, base_url: "https://b.example.com/x", version: "/v1", default: true }
`,
		},
		{
			name: "two rows, exactly one with an empty path_prefix",
			why:  "The catch-all rung: with no declared default, a single bare-host row is the canonical endpoint. Ordered so the catch-all is SECOND, so rows[0] gives the wrong answer.",
			yaml: `provider_routes:
  - { host: "a.example.com", path_prefix: "/x", protocol: openai_compatible, provider: synth, base_url: "https://a.example.com/x", version: "/v1" }
  - { host: "b.example.com", protocol: openai_compatible, provider: synth, base_url: "https://b.example.com", version: "/v1" }
`,
		},
		{
			name: "single row",
			why:  "The common case, kept so the fixture also pins the easy rung.",
			yaml: `provider_routes:
  - { host: "a.example.com", protocol: openai_compatible, provider: synth, base_url: "https://a.example.com", version: "/v1" }
`,
		},
		{
			name: "no rows at all",
			why:  "An unknown pair. Trivially a refusal, but pinned so the TS helper cannot throw on an empty list.",
			yaml: "provider_routes: []\n",
		},
	}

	out := make([]crossLangSynthetic, 0, len(scenarios))
	for _, sc := range scenarios {
		tbl, err := Parse([]byte(sc.yaml))
		if err != nil {
			panic("providerroutes: synthetic scenario " + sc.name + " does not parse: " + err.Error())
		}
		item := crossLangSynthetic{Name: sc.name, Why: sc.why}
		// Non-nil so the fixture emits [] rather than null: the TS helper takes
		// an array, and `null.length` would throw instead of asserting.
		item.Rows = []struct {
			URL        string `json:"url"`
			Host       string `json:"host"`
			PathPrefix string `json:"pathPrefix"`
			IsDefault  bool   `json:"isDefault"`
		}{}
		for _, r := range tbl.All() {
			item.Rows = append(item.Rows, struct {
				URL        string `json:"url"`
				Host       string `json:"host"`
				PathPrefix string `json:"pathPrefix"`
				IsDefault  bool   `json:"isDefault"`
			}{EffectiveUpstream(r), r.Host, r.PathPrefix, r.Default})
		}
		// The protocol/provider are uniform within each scenario; read them off
		// the first row so this stays data-driven.
		if len(tbl.All()) > 0 {
			first := tbl.All()[0]
			route, ok := tbl.ByProviderProtocol(first.Provider, first.Protocol)
			item.WantOK = ok
			if ok {
				item.WantURL = EffectiveUpstream(route)
			}
		}
		out = append(out, item)
	}
	return out
}

// TestExportCrossLangAnswers regenerates testdata/crosslang_answers.json.
//
//	AIKEY_REGEN_CROSSLANG=1 go test ./pkg/providerroutes -run TestExportCrossLangAnswers
func TestExportCrossLangAnswers(t *testing.T) {
	if os.Getenv("AIKEY_REGEN_CROSSLANG") != "1" {
		t.Skip("generator; set AIKEY_REGEN_CROSSLANG=1 to rewrite the fixture")
	}
	blob, err := json.MarshalIndent(buildCrossLangAnswers(), "", "  ")
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	out := filepath.Join("testdata", "crosslang_answers.json")
	if err := os.WriteFile(out, append(blob, '\n'), 0o644); err != nil {
		t.Fatalf("write %s: %v", out, err)
	}
	t.Logf("wrote %s", out)
}

// TestFence_CrossLangAnswersAreCurrent keeps the checked-in fixture honest.
// Without it the TS test could pass against a fixture describing a table that
// no longer exists — green on both sides, agreeing about the past.
func TestFence_CrossLangAnswersAreCurrent(t *testing.T) {
	blob, err := os.ReadFile(filepath.Join("testdata", "crosslang_answers.json"))
	if err != nil {
		t.Fatalf("read crosslang fixture: %v", err)
	}
	var stored crossLangAnswers
	if err := json.Unmarshal(blob, &stored); err != nil {
		t.Fatalf("unmarshal crosslang fixture: %v", err)
	}
	if len(stored.ByProviderProtocol) == 0 {
		t.Fatal("fixture has zero pairs — anti-vacuous assertion")
	}
	fresh := buildCrossLangAnswers()

	freshBlob, _ := json.Marshal(fresh)
	storedBlob, _ := json.Marshal(stored)
	if string(freshBlob) != string(storedBlob) {
		t.Errorf("testdata/crosslang_answers.json is STALE — the routing table changed but the "+
			"cross-language fixture did not.\n"+
			"  The TS parity test compares against this file, so leaving it stale makes BOTH sides "+
			"green while agreeing about a table that no longer exists.\n"+
			"  Regenerate: AIKEY_REGEN_CROSSLANG=1 go test ./pkg/providerroutes -run TestExportCrossLangAnswers\n"+
			"  (pairs: fixture %d, current %d)", len(stored.ByProviderProtocol), len(fresh.ByProviderProtocol))
	}
}
